version: '3.8'
services:
  web:
    build: .
    ports:
    - "80:80"
    volumes:
    - .:/opt
    - /Users/pavelzagalsky/.aws/:/home/app/.aws/:ro # Substitute $HOME with the path to your home directory
    - /Users/pavelzagalsky/.gcp/:/home/app/.gcp/:ro # Substitute $HOME with the path to your home directory
    environment:
      MONGO_URL: mongodb
      MONGO_PORT: 27017
      MONGO_PASSWORD: s3cr3t
      MONGO_USER: pavel
      GITHUB_ACTION_TOKEN:
      PROJECT_NAME: trolley
      GITHUB_REPOSITORY: Trolley-MGMT/Trolley-Management
      SECRET_KEY: J-r08vCLGU8uNib01HpUSuh7fbZWJ1FTzCiYxh7TRyo=
      AWS_SHARED_CREDENTIALS_FILE: /home/app/.aws/credentials
      AWS_DEFAULT_REGION: us-east-1
      GCP_CREDENTIALS_FILE: /home/app/.gcp/gcp_credentials
      DOCKER_ENV: Yes
    networks:
      - frontend
      - backend
  mongodb:
    image: 'mongo'
    container_name: 'mongo-db'
    command: mongod --auth
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pavel
      - MONGO_INITDB_ROOT_PASSWORD=s3cr3t
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodbdata:/data/db
    ports:
      - '27027:27017'
      - '27028:27018'
      - '27029:27019'
    networks:
      - frontend
      - backend
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
volumes:
  mongodbdata:
    driver: local