
# OS
MACOS = 'macOS'

# GKE
CLUSTER_TYPE = 'cluster_type'
GKE = 'gke'
GKE_AUTOPILOT = 'gke_autopilot'
TROLLEY_PROJECT_NAME = 'trolley'

PROJECT_NAME = 'PROJECT_NAME'
CLUSTER_NAME = 'CLUSTER_NAME'
CLUSTER_VERSION = 'CLUSTER_VERSION'
NUM_NODES = 'NUM_NODES'
EXPIRATION_TIME = 'EXPIRATION_TIME'
ZONE_NAME = 'zone_name'
IMAGE_TYPE = 'IMAGE_TYPE'
REGION_NAME = 'REGION_NAME'
GET = 'GET'
POST = 'POST'
