
# OS
MACOS = 'macOS'


# GKE
CLUSTER_TYPE = 'cluster_type'
GKE = 'gke'
GKE_AUTOPILOT = 'gke_autopilot'
TROLLEY_PROJECT_NAME = 'trolley'

# GENERAL
HELM_INSTALLS = 'HELM_INSTALLS'
PROJECT_NAME = 'PROJECT_NAME'
CLUSTER_NAME = 'CLUSTER_NAME'
CLUSTER_VERSION = 'CLUSTER_VERSION'
NUM_NODES = 'NUM_NODES'
EXPIRATION_TIME = 'EXPIRATION_TIME'
ZONE_NAME = 'zone_name'
IMAGE_TYPE = 'IMAGE_TYPE'
REGION_NAME = 'REGION_NAME'
GET = 'GET'
POST = 'POST'
APPLICATION_JSON = 'application/json'
# EKS
VERSION = 'version'
EKS = 'eks'


# AKS
AKS_VERSION = 'AKS_VERSION'
AKS_LOCATION = 'AKS_LOCATION'