name: AKS Deletion
on:
  repository_dispatch:
    types: aks-delete-api-trigger

jobs:
  delete-aks-cluster:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Echo the values
        run: |
          echo "${{ github.event.client_payload.cluster_name }}"
          echo "${{ github.event.client_payload.azure_credentials }}"


      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ github.event.client_payload.azure_credentials }}


      - name: Set Azure Subscription
        run: az account set --subscription ${{ github.event.client_payload.az_subscription_id }}

      - name: Deleting Cluster
        if: always()
        env:
          MONGO_URL: ${{ github.event.client_payload.mongo_url }}
          MONGO_USER: ${{ github.event.client_payload.mongo_user }}
          MONGO_PASSWORD: ${{ github.event.client_payload.mongo_password }}
          CLUSTER_NAME: ${{ github.event.client_payload.cluster_name }}
          RESOURCE_GROUP: ${{ github.event.client_payload.az_resource_group }}

        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 deployment_utils/set_cluster_availability.py --cluster_type aks --cluster_name ${{ github.event.client_payload.cluster_name }}} --availability False
          az aks delete --name=${{ github.event.client_payload.cluster_name }} --resource-group=Trolley --yes