name: AKS Caching
on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  aks_caching:
    runs-on: ubuntu-20.04
    steps:
      - uses: 'actions/checkout@v3'

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Caching Tasks
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}

        run: |
          brew install az
          which az
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 web/scripts/aks_caching_script.py