name: AWS Periodical Caching
on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: branch_name
        default: master
      project_name:
        required: true
        description: project_name
        default: trolley
  schedule:
    - cron: "0 1 * * *"

jobs:
  aws_caching:
    runs-on: ubuntu-22.04
    steps:
      - uses: 'actions/checkout@v3'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Caching Tasks
        if: always()
        run: |
          export MONGO_URL=${{ secrets.MONGO_URL }}
          export MONGO_USER=${{ secrets.MONGO_USER }}
          export MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
          export PROJECT_NAME=${{ github.event.inputs.project_name }}
          export GITHUB_ACTIONS_ENV=Yes
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 web/scripts/aws_caching_script.py --aws-access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --aws-secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}