name: AWS Caching
on:
  repository_dispatch:
    types: aws-caching-action-trigger

jobs:
  aws-caching-trigger:
    runs-on: ubuntu-22.04
    steps:
      - uses: 'actions/checkout@v3'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ github.event.client_payload.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.client_payload.aws_secret_access_key }}
          aws-region: us-east-1

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Echo the values
        run: |
          echo "project_name is: ${{ github.event.client_payload.project_name }}"
        

      - name: Caching Tasks
        if: always()
        run: |
          export MONGO_URL=${{ github.event.client_payload.mongo_url }}
          export MONGO_USER=${{ github.event.client_payload.mongo_user }}
          export MONGO_PASSWORD=${{ github.event.client_payload.mongo_password }}
          export PROJECT_NAME=${{ github.event.client_payload.project_name }}
          export INFRACOST_TOKEN=${{ github.event.client_payload.infracost_token }}
          export SECRET_KEY=${{ secrets.SECRET_KEY }}
          export GITHUB_ACTIONS_ENV=Yes
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          pytest web/scripts/tests/test_aws_caching_script --aws-access-key-id ${{ github.event.client_payload.aws_access_key_id }} --aws-secret-access-key ${{ github.event.client_payload.aws_secret_access_key }}
          python3 web/scripts/aws_caching_script.py --aws-access-key-id ${{ github.event.client_payload.aws_access_key_id }} --aws-secret-access-key ${{ github.event.client_payload.aws_secret_access_key }}