name: AZ Caching
on:
  repository_dispatch:
    types: az-caching-action-trigger

jobs:
  az_caching:
    runs-on: ubuntu-20.04
    steps:
      - uses: 'actions/checkout@v3'

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Echo the values
        run: |
          echo "client_payload is: ${{ github.event.client_payload.client_payload }}"
          echo "azure_client_id is: ${{ github.event.client_payload.azure_client_id }}"      
          echo "azure_tenant_id is: ${{ github.event.client_payload.azure_tenant_id }}"      
          echo "azure_subscription_id is: ${{ github.event.client_payload.azure_subscription_id }}"      
          echo "project_name is: ${{ github.event.client_payload.project_name }}"

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ github.event.client_payload.azure_client_id }}"
          tenant-id: ${{ github.event.client_payload.azure_tenant_id }}"
          subscription-id: ${{ github.event.client_payload.azure_subscription_id }}"

      - name: Caching Tasks
        env:
          MONGO_URL: ${{ github.event.client_payload.mongo_url }}
          MONGO_USER: ${{ github.event.client_payload.mongo_user }}
          MONGO_PASSWORD: ${{ github.event.client_payload.mongo_password }}
          PROJECT_NAME: ${{ github.event.client_payload.project_name }}
          GITHUB_ACTIONS_ENV: Yes

        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/runner/.bash_profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install az
          which az
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 web/scripts/aks_caching_script.py