name: AZ Periodical Caching
on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: branch_name
        default: master
      project_name:
        required: true
        description: project_name
        default: trolley
  schedule:
    - cron: "*/5 * * * *"

jobs:
  az_caching:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: 'actions/checkout@v3'

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9


      - name: Az CLI login
        uses: Azure/login@v1
        env:
          CREDENTIALS: ${{ secrets.azure_credentials }}
        with:
          creds: ${{ env.CREDENTIALS }}

      - name: Echo the values
        run: |
          echo "project_name is: ${{ github.event.inputs.project_name }}

      - name: Caching Tasks
        if: always()
        run: |
          export MONGO_URL=${{ secrets.MONGO_URL }}
          export MONGO_USER=${{ secrets.MONGO_USER }}
          export MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
          export PROJECT_NAME=${{ github.event.inputs.project_name }}
          export GITHUB_ACTIONS_ENV=Yes
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 web/scripts/az_caching_script.py
