name: EKS Deletion
on:
  repository_dispatch:
    types: eks-delete-api-trigger

jobs:
  delete-eks-cluster:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Echo the values
        run: |
          echo "region_name is: ${{ github.event.client_payload.region_name }}"
          echo "cluster_name is: ${{ github.event.client_payload.cluster_name }}"

      - name: Echo the values
        run: |
          echo "${{ github.event.client_payload.cluster_version }}"
          echo "${{ github.event.client_payload.region_name }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ github.event.client_payload.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.client_payload.aws_secret_access_key }}
          aws-region: us-east-1

      - name: Install EKSctl
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          export KUBECONFIG=/home/runner/.kube/config
          aws sts get-caller-identity
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          which helm >> /tmp/helm_path
          brew install eksctl
          eksctl delete cluster --region=${{ github.event.client_payload.region_name }} --name=${{ github.event.client_payload.cluster_name }}

      - name: Deleting Cluster
        if: always()
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 deployment_utils/set_cluster_availability.py --cluster_type eks --cluster_name ${{ github.event.client_payload.cluster_name }} --availability False
