name: Expired Clusters Deletion
on:
#  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"

jobs:
  expired_clusters_deletion:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Post Deployment Tasks
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          GITHUB_ACTION_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          export PYTHONPATH=/home/runner/work/Trolley-Management/Trolley-Management
          pip3 install -r web/requirements.txt
          cd web/scripts
          python3 expired_clusters_deletion.py --cluster_type gke
          python3 expired_clusters_deletion.py --cluster_type eks
          python3 expired_clusters_deletion.py --cluster_type aks