name: Expired Clusters Deletion
on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: branch_name
        default: master
  schedule:
    - cron: "5 * * * *"

jobs:
  expired_clusters_deletion:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Expired Cluster Script
        env:
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 web/scripts/expired_clusters_deletion.py --cluster_type gke
          python3 web/scripts/expired_clusters_deletion.py --cluster_type eks
          python3 web/scripts/expired_clusters_deletion.py --cluster_type aks