name: GCP Caching
on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: branch_name
        default: master
#on:
#  schedule:
#    - cron: "0 1 * * *"

jobs:
  gcp_caching:
    runs-on: ubuntu-20.04
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDS_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: gcloud info
      - name: Installing GCloud and Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          which helm >> /tmp/helm_path
          export KUBECONFIG=/tmp/kubeconfig
          gcloud container images list
          gcloud components install beta --quiet
          cat $GOOGLE_APPLICATION_CREDENTIALS
          export GOOGLE_CREDS_CONTENT=$(cat $GOOGLE_APPLICATION_CREDENTIALS)
          echo $GOOGLE_CREDS_CONTENT >> /home/app/.gcp/gcp_credentials.json
          echo "google_creds_content=$(cat $GOOGLE_APPLICATION_CREDENTIALS)" >> $GITHUB_ENV


      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Caching Tasks
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}

        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 web/scripts/gcp_caching_script.py
