name: GCP Caching

on:
  repository_dispatch:
    types: gcp-caching-action-trigger

jobs:
  gcp-caching-trigger:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Echo the values
        run: |
          echo "client_payload is: ${{ github.event.client_payload.client_payload }}"
          echo "google_creds_json is: ${{ github.event.client_payload.google_creds_json }}"          


      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ github.event.client_payload.google_creds_json }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: |
          gcloud info
          cat $GOOGLE_APPLICATION_CREDENTIALS
          export GOOGLE_CREDS_CONTENT=$(cat $GOOGLE_APPLICATION_CREDENTIALS)
          echo $GOOGLE_CREDS_CONTENT >> /home/runner/work/gcp_credentials.json
          echo "google_creds_content=$(cat $GOOGLE_APPLICATION_CREDENTIALS)" >> $GITHUB_ENV

      - name: Caching Tasks
        env:
          MONGO_URL: ${{ github.event.client_payload.mongo_url }}
          MONGO_USER: ${{ github.event.client_payload.mongo_user }}
          MONGO_PASSWORD: ${{ github.event.client_payload.mongo_password }}
          PROJECT_NAME: ${{ github.event.client_payload.project_name }}
          GITHUB_ACTIONS_ENV: Yes

        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 web/scripts/gcp_caching_script.py