name: GCP Caching

on:
  repository_dispatch:
    types: gcp-caching-action-trigger

jobs:
  gcp-caching-trigger:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Checkout infracost pricing repo
        uses: actions/checkout@v3
        with:
          repository: infracost/cloud-pricing-api
          path: cloud-pricing-api


      - name: Echo the values
        run: |
          echo "client_payload is: ${{ github.event.client_payload.client_payload }}"
          echo "google_creds_json is: ${{ github.event.client_payload.google_creds_json }}"      
          echo "project_name is: ${{ github.event.client_payload.project_name }}"
          echo "infracost_token is: ${{ github.event.client_payload.infracost_token }}"
      

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ github.event.client_payload.google_creds_json }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: |
          gcloud info
          cat $GOOGLE_APPLICATION_CREDENTIALS
          export GOOGLE_CREDS_CONTENT=$(cat $GOOGLE_APPLICATION_CREDENTIALS)
          echo $GOOGLE_CREDS_CONTENT >> /home/runner/work/gcp_credentials.json
          echo "google_creds_content=$(cat $GOOGLE_APPLICATION_CREDENTIALS)" >> $GITHUB_ENV

      - name: Caching Tasks
        if: always()
        run: |
          cd cloud-pricing-api
          export SELF_HOSTED_INFRACOST_API_KEY="${{ github.event.client_payload.infracost_token }}"
          export INFRACOST_API_KEY="${{ github.event.client_payload.infracost_token }}"
          docker-compose run init_job
          docker-compose up -d api
          curl --retry 20 --retry-all-errors http://localhost:4000/health
          export MONGO_URL=${{ github.event.client_payload.mongo_url }}
          export MONGO_USER=${{ github.event.client_payload.mongo_user }}
          export MONGO_PASSWORD=${{ github.event.client_payload.mongo_password }}
          export PROJECT_NAME=${{ github.event.client_payload.project_name }}
          export INFRACOST_TOKEN=${{ github.event.client_payload.infracost_token }}
          export INFRACOST_URL=http://localhost:4000
          export GITHUB_ACTIONS_ENV=Yes
          export PYTHONPATH=$PYTHONPATH:.
          cd ..
          pip3 install -r web/requirements.txt
          python3 web/scripts/gcp_caching_script.py