name: GCP Periodical Caching

on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: branch_name
        default: master
      project_name:
        required: true
        description: project_name
        default: trolley
  schedule:
    - cron: "*/5 * * * *"

jobs:
  gcp_caching:
    runs-on: ubuntu-22.04
    steps:
      - uses: 'actions/checkout@v3'
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDS_JSON }}


      - name: Echo the values
        run: |
          echo "default_project_name is: ${{ secrets.DEFAULT_PROJECT_NAME }}"
          

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: gcloud info
      - name: Installing GCloud
        run: |
          export KUBECONFIG=/tmp/kubeconfig
          gcloud container images list
          gcloud components install beta --quiet
          cat $GOOGLE_APPLICATION_CREDENTIALS
          export GOOGLE_CREDS_CONTENT=$(cat $GOOGLE_APPLICATION_CREDENTIALS)
          echo $GOOGLE_CREDS_CONTENT >> /home/runner/work/gcp_credentials.json
          echo "google_creds_content=$(cat $GOOGLE_APPLICATION_CREDENTIALS)" >> $GITHUB_ENV


      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9


      - name: Caching Tasks
        if: always()
        run: |
          export MONGO_URL=${{ secrets.MONGO_URL }}
          export MONGO_USER=${{ secrets.MONGO_USER }}
          export MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}
          export PROJECT_NAME=${{ github.event.inputs.project_name }}
          export DEFAULT_PROJECT_NAME=${{ secrets.DEFAULT_PROJECT_NAME }}
          export GITHUB_ACTIONS_ENV=Yes
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 web/scripts/gcp_caching_script.py
