name: Helm Caching
on:
  workflow_dispatch

jobs:
  helm_caching:
    runs-on: ubuntu-20.04
    steps:
      - uses: 'actions/checkout@v3'

      - name: Installing Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          which helm >> /tmp/helm_path

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Caching Tasks
        env:
          MONGO_URL: ${{ secrets.MONGO_URL }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}

        run: |
          export PYTHONPATH=$PYTHONPATH:.
          pip3 install -r web/requirements.txt
          python3 web/scripts/helm_caching_script.py