name: Trolley Server Manual Build Image
on:
  workflow_dispatch:
    inputs:
      branch_name:
        required: true
        description: branch_name
        default: master

jobs:
  build_trolley_server_docker_image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9


      - name: Extracting Trolley version
        run: |
          export PYTHONPATH='/home/runner/work/trolleymgmt/trolleymgmt/web'
          python3 -c "from __init__ import __version__; print(__version__)" > trolley_version_tag
          cat trolley_version_tag
          echo "trolley_version_tag=$(cat trolley_version_tag)" >> $GITHUB_ENV
          

      - name: Checking the values
        run: |
          echo "The docker_tag tag is: ${{ env.docker_tag }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Dockerhub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        run: |
          docker buildx build --push --platform linux/arm64,linux/amd64  -t  pavelzagalsky/trolley_server:${{ env.trolley_version_tag }}  -f Dockerfile .