name: Trolley Test
on:
  push:
    branches:
      - master

jobs:
  test_run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDS_JSON }}



      - name: Az CLI login
        uses: Azure/login@v1
        env:
          CREDENTIALS:  ${{ secrets.AZURE_CREDENTIALS }}
        with:
          creds: ${{ env.CREDENTIALS }}


      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Use gcloud CLI
        run: |
          gcloud info
          cat $GOOGLE_APPLICATION_CREDENTIALS
          export GOOGLE_CREDS_CONTENT=$(cat $GOOGLE_APPLICATION_CREDENTIALS)
          echo $GOOGLE_CREDS_CONTENT >> /home/runner/work/gcp_credentials.json
          echo "google_creds_content=$(cat $GOOGLE_APPLICATION_CREDENTIALS)" >> $GITHUB_ENV


      - name: Running Tests
        run: |
          export GITHUB_ACTIONS_ENV=Yes
          export PYTHONPATH=$PYTHONPATH:.
          export SECRET_KEY=${{ secrets.SECRET_KEY }}
          export MONGO_URL=${{ secrets.mongo_url }}
          export MONGO_USER=${{ secrets.mongo_user }}
          export MONGO_PASSWORD=${{ secrets.mongo_password }}
          export PROJECT_NAME=${{ secrets.project_name }}
          export INFRACOST_TOKEN=${{ secrets.infracost_token }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          pip3 install -r web/requirements.txt
          pytest web/scripts/tests/test_az_caching_script.py
          pytest web/scripts/tests/test_gcp_caching_script.py
          pytest web/scripts/tests/test_aws_caching_script.py --aws-access-key-id ${{ secrets.AWS_ACCESS_KEY_ID }} --aws-secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

